# Generated by Django 5.0.3 on 2024-03-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cineapp', '0002_pelicula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, verbose_name='Nombre de usuario')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=250, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=250, verbose_name='Contraseña')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usuariouserpermissions',
            name='Usuarios',
        ),
        migrations.RemoveField(
            model_name='usuariouserpermissions',
            name='permission',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de agregado a la base de datos'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=250, null=True, verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duration',
            field=models.PositiveIntegerField(null=True, verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genre',
            field=models.CharField(max_length=100, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='language',
            field=models.CharField(max_length=50, null=True, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='lead_actors',
            field=models.TextField(null=True, verbose_name='Actores principales'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters/', verbose_name='Póster'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Calificación'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='release_year',
            field=models.PositiveIntegerField(null=True, verbose_name='Año de lanzamiento'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='trailer',
            field=models.URLField(null=True, verbose_name='Enlace al tráiler'),
        ),
        migrations.DeleteModel(
            name='UsuarioGroups',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='UsuarioUserPermissions',
        ),
    ]
